### ISSUE TITLE
Add gerber files

### ISSUE THREAD

**Issue by thijstriemstra** [CoretechR/OMOTE#1]
Would be great to have the gerber/bom/placement files so it can be produced by a company like JLPCB or PCBWay.

I tried exporting it from Kicad 7 but there are so many options, not sure what to do, I'm new to this.

**Comment by CoretechR** [comment]
Hi, you're right, I will add those files to the repository soon.
Until then there are plugins for both JLCPCB and PCBWay in KiCad that work really well.

**Comment by mandreko** [comment]
I just generated these in KiCad in a way that has worked for me for previous PCBs, if it's helpful.

[OMOTE_gerber_20230707.zip](https://github.com/CoretechR/OMOTE/files/11985526/OMOTE_gerber_20230707.zip)

**Comment by thijstriemstra** [comment]
thanks @mandreko. I believe we'll also need the bom and placement csv files for jlpcb (?).

**Comment by CoretechR** [comment]
Added the GERBER files (7b5d897)
These were exported by the JLCPCB plugin, but should work for other manufacturers as well.
