### ISSUE TITLE
Some parts models are missing from the kicad project

### ISSUE THREAD

**Issue by Dark1886** [CoretechR/OMOTE#19]
Some of the footprints/models for components are pointing to a /mkern/ library that does not seem to be stock in the kicad application. If these are custom footprints, can those models be shared?

**Comment by CoretechR** [comment]
Hi, these are custom made footprints. I can add them to the repository when I get back to my PC. 
The footprints should also be included in the KiCad pcb file, they are just not directly accessible.

**Comment by Dark1886** [comment]
@CoretechR Just pinging you again in case you forgot. I'd like to try and update some of the footprints and create a package that will be more easily 'drag-and-drop'ed into JLCPCB or PCBWay without needing to do additional part orientation/placement updates.

**Comment by CoretechR** [comment]
@Dark1886 I am still new to KiCad so it took a while :)
The missing files are now inside "omoteLib" as a project-specific library.
Maybe you can check if everything's accounted for.

**Comment by Dark1886** [comment]
No Problem, I'll take a look at that in the near future.

**Comment by CoretechR** [comment]
@Dark1886 Did you have time to look at the footprints?

**Comment by Dark1886** [comment]
I did load the files you added as custom parts and it did load in correctly.
