### ISSUE TITLE
Fredoka Light font missing

### ISSUE THREAD

**Issue by mandreko** [CoretechR/OMOTE#4]
When I initially open the PCB designer, I get a message that the Fredoka Light font is missing, since it's not a system font. I'm not sure if it's super important to have that specific font, but if so, it might make sense to include it in the repository and reference it.

**Comment by CoretechR** [comment]
Solved in 0784a3b
I created most of the labels with the KiBuzzard Plugin except for the XYZ letters near the accelerometer. These are switched over to KiBuzzard as well now so you do not need the Fredoka font anymore.
