### ISSUE TITLE
C15 too small for reliable uploads with Windows 11

### ISSUE THREAD

**Issue by KlausMu** [CoretechR/OMOTE#62]
Hi Max,

I always had the issue that it was not possible for me to do the firmware upload with PlatformIO on Windows.
On the same computer, same USB port, same hardware, the upload was possible from WSL2.
Obviously the drivers on Windows and Ubuntu handle EN and GPIO0 slightly differently.
It was always a pain for me to switch between Windows for compiling and WSL2 for uploading.

On Windows this is a [widely known problem.](https://github.com/espressif/esptool/issues/706)
Sometimes older driver versions help, but not in my case. I tried a lot of different driver versions and driver settings.

I have only basic knowledge about wiring, PCBs and so on, but I found this:
https://docs.espressif.com/projects/esptool/en/latest/esp32/advanced-topics/boot-mode-selection.html#boot-mode
_If this circuitry is implemented (all Espressif boards have it), adding a capacitor between the EN pin and GND **(in the 1uF-10uF range)** is necessary for the reset circuitry to work reliably. This is shown in the ESP32 Module section of the schematic._

As far as I understand, the OMOTE has 100 nF as capacitor (C15) between EN and GND. Espressif recommends 1uF-10uF. So I added 10uF in parallel.

![image](https://github.com/CoretechR/OMOTE/assets/14290221/adb21568-5f46-45e9-9f5a-790da600727e)

This did the trick. No more switching between Windows and WSL2.

As you are currently working on a new version of the PCB, maybe you want to think about increasing C15.

**Comment by CoretechR** [comment]
Hi Klaus, that is a good point. I never had a problem with the automatic reset on my own boards with 100nF but Espressif does indeed recommend a higher capacitance. They somehow do not follow their own recommendation and only put 100nF on all their evaluation boards, but that might explain why the reset never works on those. Maybe they wanted to save 1 cent on their boards. 
I will definitely put that on my list for the new revision, thank you!
