### ISSUE TITLE
Discord Link corrent?

### ISSUE THREAD

**Issue by bjoerns1983** [CoretechR/OMOTE#65]
Hi there,
is the Discord Link in the readme still correct?

**Comment by KlausMu** [comment]
Yes, for me it works. https://discord.com/channels/1138116475559882852/1153343867681243279

**Comment by aristeu** [comment]
Link doesn't work for me either. Wondering if the server requires invite. Someone could create an invite (down arrow on the server icon, invite people, edit invite link, set it to not expire) and replace that link in the documentation.

**Comment by CoretechR** [comment]
That is strange. Discord shows me that the link in the readme is active and set to never expire. 
![image](https://github.com/CoretechR/OMOTE/assets/13223470/d37ae3ea-f844-431c-be2d-e06435f5e21c)

**Comment by aristeu** [comment]
The format for invite URLs are

```
https://discord.gg/<10 characters>
```

while the link looks like something it'd be copied from the URL bar while browsing the server/channel.
This is what shows when clicking on the link (in a browser I'm authenticated at discord):

![discord](https://github.com/CoretechR/OMOTE/assets/348861/02b9a49a-1139-4254-8e95-640826066c0d)

You might be able to reproduce the issue by logging off your discord account (or using a different browser you're not authenticated).

**Comment by CoretechR** [comment]
Are we talking about this link?
https://discord.gg/5PnYFAsKsG

Because it works for me. I also tried it in incognito mode. Or what other link is there in the readme?

**Comment by aristeu** [comment]
Ah, I see what's happening. I clicked on the Discord link to buy the PCB channel:

```
Check out the buy-sell page on the [Discord](https://discord.com/channels/1138116475559882852/1153343867681243279) to see if you can share the cost of the PCBs and components with others.
```

And didn't get to the end of the page so I didn't see the invite. Invite link works, thanks.

**Comment by Dark1886** [comment]
@CoretechR otherwise use this link in the readme 

https://discord.gg/cTR5d8AYFj
