### ISSUE TITLE
OMOTE Rev3.pdf cannot be opened

### ISSUE THREAD

**Issue by Insomniac80** [CoretechR/OMOTE#7]
Hiho,

[OMOTE Rev3.pdf](https://github.com/CoretechR/OMOTE/blob/main/PCB/OMOTE%20Rev3.pdf) seems to be broken. 

Best regards

**Comment by CoretechR** [comment]
Hi, what software are sou using? It works fine for me with the browser and Acrobat.

**Comment by riker09** [comment]
I can open and view it on my Android as well
