### ISSUE TITLE
BOM Fixes

### ISSUE THREAD

**Issue by mandreko** [CoretechR/OMOTE#8]
You previously went through and added the BOM in #3 but I found a couple minor discrepancies when looking at parts today:

1. R1; R38; R39; R40 has a quantity of "2" listed, when it should be "4"
2. R6; R11; R12; R13; R14; R19; R20; R22; R26; R30; R31; R32; R33; R34; R35; R37 has a quantity of "15" listed, when it should be "16"
3. J4 is missing. It looks to be just a standard pin header that most people building this probably have sitting around, but for "completeness", it should probably be added

**Comment by CoretechR** [comment]
I missed that, thank you! The pin header is really just for measuring current consumption by suppling the board from an external power supply.
